"""Ripgrep lane contracts/codecs/runtime helpers."""

from __future__ import annotations

from tools.cq.search.rg.codec import (
    RgAnyEvent,
    RgEvent,
    RgMatchData,
    RgMatchEvent,
    RgPath,
    RgSubmatch,
    RgSummaryData,
    RgSummaryEvent,
    RgSummaryStats,
    RgText,
    as_match_data,
    as_summary_data,
    decode_event,
    decode_event_strict,
    decode_rg_event,
    decode_rg_event_mapping,
    match_line_number,
    match_line_text,
    match_path,
    submatch_text,
    summary_stats,
)
from tools.cq.search.rg.collector import collect_events
from tools.cq.search.rg.contracts import (
    RgProcessResultV1,
    RgRunSettingsV1,
    result_from_process,
    settings_from_request,
)
from tools.cq.search.rg.runner import (
    RgProcessResult,
    build_command_from_settings,
    build_rg_command,
    detect_rg_types,
    detect_rg_version,
    run_rg_json,
    run_rg_json_contract,
    run_with_request,
    run_with_settings,
)

__all__ = [
    "RgAnyEvent",
    "RgEvent",
    "RgMatchData",
    "RgMatchEvent",
    "RgPath",
    "RgProcessResult",
    "RgProcessResultV1",
    "RgRunSettingsV1",
    "RgSubmatch",
    "RgSummaryData",
    "RgSummaryEvent",
    "RgSummaryStats",
    "RgText",
    "as_match_data",
    "as_summary_data",
    "build_command_from_settings",
    "build_rg_command",
    "collect_events",
    "decode_event",
    "decode_event_strict",
    "decode_rg_event",
    "decode_rg_event_mapping",
    "detect_rg_types",
    "detect_rg_version",
    "match_line_number",
    "match_line_text",
    "match_path",
    "result_from_process",
    "run_rg_json",
    "run_rg_json_contract",
    "run_with_request",
    "run_with_settings",
    "settings_from_request",
    "submatch_text",
    "summary_stats",
]
