"""Relationship spec models, registry, and compiler."""

from arrowdsl.spec.infra import DATASET_REF_STRUCT, SORT_KEY_STRUCT
from relspec.compiler import (
    CompiledOutput,
    CompiledRule,
    FilesystemPlanResolver,
    InMemoryPlanResolver,
    PlanResolver,
    RelationshipRuleCompiler,
)
from relspec.contracts import (
    RELATION_OUTPUT_NAME,
    RELATION_OUTPUT_SCHEMA,
    relation_output_contract,
    relation_output_schema,
    relation_output_spec,
)
from relspec.model import (
    AddLiteralSpec,
    AmbiguityPolicy,
    CanonicalSortKernelSpec,
    ConfidencePolicy,
    DatasetRef,
    DedupeKernelSpec,
    DropColumnsSpec,
    EvidenceSpec,
    ExplodeListSpec,
    HashJoinConfig,
    IntervalAlignConfig,
    KernelSpec,
    ProjectConfig,
    RelationshipRule,
    RenameColumnsSpec,
    RuleKind,
    WinnerSelectConfig,
)
from relspec.registry import ContractCatalog, DatasetCatalog, DatasetLocation
from relspec.rules.spec_tables import (
    AMBIGUITY_STRUCT,
    CONFIDENCE_STRUCT,
    EVIDENCE_STRUCT,
    HASH_JOIN_STRUCT,
    INTERVAL_ALIGN_STRUCT,
    PROJECT_EXPR_STRUCT,
    PROJECT_STRUCT,
    RULES_SCHEMA,
    WINNER_SELECT_STRUCT,
)

__all__ = [
    "AMBIGUITY_STRUCT",
    "CONFIDENCE_STRUCT",
    "DATASET_REF_STRUCT",
    "EVIDENCE_STRUCT",
    "HASH_JOIN_STRUCT",
    "INTERVAL_ALIGN_STRUCT",
    "PROJECT_EXPR_STRUCT",
    "PROJECT_STRUCT",
    "RELATION_OUTPUT_NAME",
    "RELATION_OUTPUT_SCHEMA",
    "RULES_SCHEMA",
    "SORT_KEY_STRUCT",
    "WINNER_SELECT_STRUCT",
    "AddLiteralSpec",
    "AmbiguityPolicy",
    "CanonicalSortKernelSpec",
    "CompiledOutput",
    "CompiledRule",
    "ConfidencePolicy",
    "ContractCatalog",
    "DatasetCatalog",
    "DatasetLocation",
    "DatasetRef",
    "DedupeKernelSpec",
    "DropColumnsSpec",
    "EvidenceSpec",
    "ExplodeListSpec",
    "FilesystemPlanResolver",
    "HashJoinConfig",
    "InMemoryPlanResolver",
    "IntervalAlignConfig",
    "KernelSpec",
    "PlanResolver",
    "ProjectConfig",
    "RelationshipRule",
    "RelationshipRuleCompiler",
    "RenameColumnsSpec",
    "RuleKind",
    "WinnerSelectConfig",
    "relation_output_contract",
    "relation_output_schema",
    "relation_output_spec",
]
