"""Relationship spec models, registry, and compiler."""

from relspec.compiler import (
    CompiledOutput,
    CompiledRule,
    FilesystemPlanResolver,
    InMemoryPlanResolver,
    PlanResolver,
    RelationshipRuleCompiler,
)
from relspec.model import (
    AddLiteralSpec,
    CanonicalSortKernelSpec,
    DatasetRef,
    DedupeKernelSpec,
    DropColumnsSpec,
    ExplodeListSpec,
    HashJoinConfig,
    IntervalAlignConfig,
    KernelSpec,
    ProjectConfig,
    RelationshipRule,
    RenameColumnsSpec,
    RuleKind,
    WinnerSelectConfig,
)
from relspec.registry import ContractCatalog, DatasetCatalog, DatasetLocation, RelationshipRegistry
from relspec.spec_tables import (
    DATASET_REF_STRUCT,
    HASH_JOIN_STRUCT,
    INTERVAL_ALIGN_STRUCT,
    PROJECT_EXPR_STRUCT,
    PROJECT_STRUCT,
    RULES_SCHEMA,
    SORT_KEY_STRUCT,
    WINNER_SELECT_STRUCT,
    relationship_rule_table,
    relationship_rules_from_table,
)

__all__ = [
    "DATASET_REF_STRUCT",
    "HASH_JOIN_STRUCT",
    "INTERVAL_ALIGN_STRUCT",
    "PROJECT_EXPR_STRUCT",
    "PROJECT_STRUCT",
    "RULES_SCHEMA",
    "SORT_KEY_STRUCT",
    "WINNER_SELECT_STRUCT",
    "AddLiteralSpec",
    "CanonicalSortKernelSpec",
    "CompiledOutput",
    "CompiledRule",
    "ContractCatalog",
    "DatasetCatalog",
    "DatasetLocation",
    "DatasetRef",
    "DedupeKernelSpec",
    "DropColumnsSpec",
    "ExplodeListSpec",
    "FilesystemPlanResolver",
    "HashJoinConfig",
    "InMemoryPlanResolver",
    "IntervalAlignConfig",
    "KernelSpec",
    "PlanResolver",
    "ProjectConfig",
    "RelationshipRegistry",
    "RelationshipRule",
    "RelationshipRuleCompiler",
    "RenameColumnsSpec",
    "RuleKind",
    "WinnerSelectConfig",
    "relationship_rule_table",
    "relationship_rules_from_table",
]
