"""Normalization helpers for extracted tables."""

from normalize.contracts import (
    NORMALIZE_EVIDENCE_NAME,
    normalize_evidence_contract,
    normalize_evidence_schema,
    normalize_evidence_spec,
)
from normalize.ibis_api import (
    DiagnosticsSources,
    add_ast_byte_spans,
    add_scip_occurrence_byte_spans,
    anchor_instructions,
    build_cfg_blocks,
    build_cfg_edges,
    build_def_use_events,
    collect_diags,
    normalize_type_exprs,
    normalize_types,
    run_reaching_defs,
)
from normalize.registry_fields import (
    DIAG_DETAIL_STRUCT,
    DIAG_DETAILS_TYPE,
    DIAG_TAGS_TYPE,
    field,
    field_name,
    fields,
)
from normalize.registry_ids import (
    DEF_USE_EVENT_ID_SPEC,
    DIAG_ID_SPEC,
    REACH_EDGE_ID_SPEC,
    TYPE_EXPR_ID_SPEC,
    TYPE_ID_SPEC,
    hash_spec,
)
from normalize.registry_specs import (
    dataset_contract,
    dataset_input_columns,
    dataset_input_schema,
    dataset_metadata_spec,
    dataset_names,
    dataset_schema,
    dataset_schema_policy,
    dataset_spec,
    dataset_specs,
    dataset_table_spec,
)
from normalize.rule_model import (
    AmbiguityPolicy,
    ConfidencePolicy,
    EvidenceSpec,
    ExecutionMode,
    NormalizeRule,
)
from normalize.runner import (
    NormalizeFinalizeSpec,
    NormalizeIbisPlanOptions,
    NormalizeRuleCompilation,
    NormalizeRunOptions,
    apply_evidence_defaults,
    apply_policy_defaults,
    compile_normalize_plans_ibis,
    ensure_canonical,
    ensure_execution_context,
    run_normalize,
)
from normalize.schema_infer import (
    SchemaInferOptions,
    align_table_to_schema,
    align_tables_to_unified_schema,
    infer_schema_from_tables,
    unify_schemas,
)
from normalize.spans import (
    build_repo_text_index,
    normalize_cst_callsites_spans,
    normalize_cst_defs_spans,
    normalize_cst_imports_spans,
)
from normalize.spec_tables import CONSTRAINTS_TABLE, CONTRACT_TABLE, FIELD_TABLE, SCHEMA_TABLES
from normalize.text_index import FileTextIndex, RepoTextIndex
from normalize.utils import add_span_id_column, span_id

__all__ = [
    "CONSTRAINTS_TABLE",
    "CONTRACT_TABLE",
    "DEF_USE_EVENT_ID_SPEC",
    "DIAG_DETAILS_TYPE",
    "DIAG_DETAIL_STRUCT",
    "DIAG_ID_SPEC",
    "DIAG_TAGS_TYPE",
    "FIELD_TABLE",
    "NORMALIZE_EVIDENCE_NAME",
    "REACH_EDGE_ID_SPEC",
    "SCHEMA_TABLES",
    "TYPE_EXPR_ID_SPEC",
    "TYPE_ID_SPEC",
    "AmbiguityPolicy",
    "ConfidencePolicy",
    "DiagnosticsSources",
    "EvidenceSpec",
    "ExecutionMode",
    "FileTextIndex",
    "NormalizeFinalizeSpec",
    "NormalizeIbisPlanOptions",
    "NormalizeRule",
    "NormalizeRuleCompilation",
    "NormalizeRunOptions",
    "RepoTextIndex",
    "SchemaInferOptions",
    "add_ast_byte_spans",
    "add_scip_occurrence_byte_spans",
    "add_span_id_column",
    "align_table_to_schema",
    "align_tables_to_unified_schema",
    "anchor_instructions",
    "apply_evidence_defaults",
    "apply_policy_defaults",
    "build_cfg_blocks",
    "build_cfg_edges",
    "build_def_use_events",
    "build_repo_text_index",
    "collect_diags",
    "compile_normalize_plans_ibis",
    "dataset_contract",
    "dataset_input_columns",
    "dataset_input_schema",
    "dataset_metadata_spec",
    "dataset_names",
    "dataset_schema",
    "dataset_schema_policy",
    "dataset_spec",
    "dataset_specs",
    "dataset_table_spec",
    "ensure_canonical",
    "ensure_execution_context",
    "field",
    "field_name",
    "fields",
    "hash_spec",
    "infer_schema_from_tables",
    "normalize_cst_callsites_spans",
    "normalize_cst_defs_spans",
    "normalize_cst_imports_spans",
    "normalize_evidence_contract",
    "normalize_evidence_schema",
    "normalize_evidence_spec",
    "normalize_type_exprs",
    "normalize_types",
    "run_normalize",
    "run_reaching_defs",
    "span_id",
    "unify_schemas",
]
