"""Centralized rule models and registries."""

from relspec.rules.compiler import RuleCompiler, RuleHandler
from relspec.rules.definitions import (
    EdgeEmitPayload,
    EvidenceOutput,
    EvidenceSpec,
    ExecutionMode,
    ExtractPayload,
    NormalizePayload,
    PolicyOverrides,
    RelationshipPayload,
    RuleDefinition,
    RuleDomain,
    RulePayload,
    RuleStage,
    RuleStageMode,
    stage_enabled,
)
from relspec.rules.diagnostics import RuleDiagnostic, rule_diagnostic_table
from relspec.rules.handlers import ExtractRuleHandler, NormalizeRuleHandler, RelationshipRuleHandler
from relspec.rules.options import RuleExecutionOptions
from relspec.rules.registry import (
    RuleAdapter,
    RuleRegistry,
    collect_rule_definitions,
)
from relspec.rules.rel_ops import (
    AggregateExpr,
    AggregateOp,
    DeriveOp,
    FilterOp,
    JoinOp,
    ParamOp,
    ProjectOp,
    PushdownFilterOp,
    RelOp,
    RelOpKind,
    RelOpT,
    ScanOp,
    UnionOp,
    query_spec_from_rel_ops,
    rel_ops_from_rows,
    rel_ops_signature,
    rel_ops_to_rows,
    validate_rel_ops,
)
from relspec.rules.relationship_specs import relationship_rule_definitions
from relspec.rules.spec_tables import (
    EXTRACT_STRUCT,
    NORMALIZE_STRUCT,
    RELATIONSHIP_STRUCT,
    RULE_DEF_SCHEMA,
    rule_definition_table,
    rule_definitions_from_table,
)
from relspec.rules.templates import RuleTemplateSpec, rule_template_table

__all__ = [
    "EXTRACT_STRUCT",
    "NORMALIZE_STRUCT",
    "RELATIONSHIP_STRUCT",
    "RULE_DEF_SCHEMA",
    "AggregateExpr",
    "AggregateOp",
    "DeriveOp",
    "EdgeEmitPayload",
    "EvidenceOutput",
    "EvidenceSpec",
    "ExecutionMode",
    "ExtractPayload",
    "ExtractRuleHandler",
    "FilterOp",
    "JoinOp",
    "NormalizePayload",
    "NormalizeRuleHandler",
    "ParamOp",
    "PolicyOverrides",
    "ProjectOp",
    "PushdownFilterOp",
    "RelOp",
    "RelOpKind",
    "RelOpT",
    "RelationshipPayload",
    "RelationshipRuleHandler",
    "RuleAdapter",
    "RuleCompiler",
    "RuleDefinition",
    "RuleDiagnostic",
    "RuleDomain",
    "RuleExecutionOptions",
    "RuleHandler",
    "RulePayload",
    "RuleRegistry",
    "RuleStage",
    "RuleStageMode",
    "RuleTemplateSpec",
    "ScanOp",
    "UnionOp",
    "collect_rule_definitions",
    "query_spec_from_rel_ops",
    "rel_ops_from_rows",
    "rel_ops_signature",
    "rel_ops_to_rows",
    "relationship_rule_definitions",
    "rule_definition_table",
    "rule_definitions_from_table",
    "rule_diagnostic_table",
    "rule_template_table",
    "stage_enabled",
    "validate_rel_ops",
]
