"""Spec tables for extract dataset registry rows."""

from __future__ import annotations

from collections.abc import Mapping

from arrowdsl.spec.tables.extract import (
    ExtractDatasetRowSpec,
    dataset_rows_from_table,
    extract_dataset_table_from_rows,
)
from extract.registry_template_specs import DATASET_TEMPLATE_SPECS
from extract.registry_templates import expand_dataset_templates

DATASET_ROW_RECORDS: tuple[Mapping[str, object], ...] = (

        {
            "name": "repo_files_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["abs_path", "size_bytes", "encoding", "text", "bytes"],
            "derived": [
                {"name": "file_id", "spec": "repo_file_id", "kind": "hash", "required": None}
            ],
            "row_fields": None,
            "row_extras": None,
            "template": "repo_scan",
            "ordering_keys": [{"column": "path", "order": "ascending"}],
            "join_keys": ["path"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_ast_nodes_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "ast_idx",
                "parent_ast_idx",
                "field_name",
                "field_pos",
                "kind",
                "name",
                "value_repr",
                "lineno",
                "col_offset",
                "end_lineno",
                "end_col_offset",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "ast",
            "ordering_keys": None,
            "join_keys": ["file_id", "ast_idx"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_ast_edges_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["parent_ast_idx", "child_ast_idx", "field_name", "field_pos"],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "ast",
            "ordering_keys": None,
            "join_keys": ["file_id", "parent_ast_idx", "child_ast_idx", "field_name", "field_pos"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_ast_errors_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["error_type", "message", "lineno", "offset", "end_lineno", "end_offset"],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "ast",
            "ordering_keys": None,
            "join_keys": ["file_id", "lineno", "offset", "end_lineno", "end_offset"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_cst_parse_manifest_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "encoding",
                "default_indent",
                "default_newline",
                "has_trailing_newline",
                "future_imports",
                "module_name",
                "package_name",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "cst",
            "ordering_keys": None,
            "join_keys": ["file_id"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_parse_manifest",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_cst_parse_errors_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["error_type", "message", "raw_line", "raw_column", "meta"],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "cst",
            "ordering_keys": None,
            "join_keys": ["file_id", "raw_line", "raw_column"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_parse_errors",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_cst_name_refs_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["name_ref_id", "span_id", "name", "expr_ctx", "bstart", "bend"],
            "derived": [
                {
                    "name": "name_ref_id",
                    "spec": "cst_name_ref_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {"name": "span_id", "spec": "span_id", "kind": "masked_hash", "required": None},
            ],
            "row_fields": None,
            "row_extras": None,
            "template": "cst",
            "ordering_keys": None,
            "join_keys": ["file_id", "bstart", "bend"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_name_refs",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_cst_imports_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "import_id",
                "span_id",
                "kind",
                "module",
                "relative_level",
                "name",
                "asname",
                "is_star",
                "stmt_bstart",
                "stmt_bend",
                "alias_bstart",
                "alias_bend",
            ],
            "derived": [
                {
                    "name": "import_id",
                    "spec": "cst_import_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "span_id",
                    "spec": "cst_import_span_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": None,
            "row_extras": None,
            "template": "cst",
            "ordering_keys": None,
            "join_keys": ["file_id", "alias_bstart", "alias_bend"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_imports",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_cst_callsites_v1",
            "version": 1,
            "bundles": ["file_identity", "call_span"],
            "fields": [
                "call_id",
                "span_id",
                "callee_bstart",
                "callee_bend",
                "callee_shape",
                "callee_text",
                "arg_count",
                "callee_dotted",
                "callee_qnames",
            ],
            "derived": [
                {"name": "call_id", "spec": "cst_call_id", "kind": "masked_hash", "required": None},
                {
                    "name": "span_id",
                    "spec": "cst_call_span_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": None,
            "row_extras": None,
            "template": "cst",
            "ordering_keys": None,
            "join_keys": ["file_id", "call_bstart", "call_bend"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_callsites",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_cst_defs_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "def_id",
                "container_def_id",
                "span_id",
                "kind",
                "name",
                "def_bstart",
                "def_bend",
                "name_bstart",
                "name_bend",
                "qnames",
            ],
            "derived": [
                {"name": "def_id", "spec": "cst_def_id", "kind": "masked_hash", "required": None},
                {
                    "name": "container_def_id",
                    "spec": "cst_container_def_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "span_id",
                    "spec": "cst_def_span_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": [
                "def_id",
                "container_def_id",
                "kind",
                "name",
                "def_bstart",
                "def_bend",
                "name_bstart",
                "name_bend",
                "qnames",
                "container_def_kind",
                "container_def_bstart",
                "container_def_bend",
            ],
            "row_extras": None,
            "template": "cst",
            "ordering_keys": None,
            "join_keys": ["file_id", "def_bstart", "def_bend"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_defs",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_cst_type_exprs_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "type_expr_id",
                "owner_def_id",
                "span_id",
                "param_name",
                "expr_kind",
                "expr_role",
                "bstart",
                "bend",
                "expr_text",
            ],
            "derived": [
                {
                    "name": "type_expr_id",
                    "spec": "cst_type_expr_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "owner_def_id",
                    "spec": "cst_owner_def_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {"name": "span_id", "spec": "span_id", "kind": "masked_hash", "required": None},
            ],
            "row_fields": [
                "type_expr_id",
                "owner_def_id",
                "param_name",
                "expr_kind",
                "expr_role",
                "bstart",
                "bend",
                "expr_text",
                "owner_def_kind",
                "owner_def_bstart",
                "owner_def_bend",
            ],
            "row_extras": None,
            "template": "cst",
            "ordering_keys": None,
            "join_keys": ["file_id", "bstart", "bend"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_type_exprs",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_bc_code_units_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "code_unit_id",
                "parent_code_unit_id",
                "qualpath",
                "co_name",
                "firstlineno",
                "argcount",
                "posonlyargcount",
                "kwonlyargcount",
                "nlocals",
                "flags",
                "stacksize",
                "code_len",
            ],
            "derived": [
                {
                    "name": "code_unit_id",
                    "spec": "bc_code_unit_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "parent_code_unit_id",
                    "spec": "bc_parent_code_unit_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": [
                "qualpath",
                "co_name",
                "firstlineno",
                "parent_qualpath",
                "parent_co_name",
                "parent_firstlineno",
                "argcount",
                "posonlyargcount",
                "kwonlyargcount",
                "nlocals",
                "flags",
                "stacksize",
                "code_len",
            ],
            "row_extras": None,
            "template": "bytecode",
            "ordering_keys": None,
            "join_keys": ["file_id", "qualpath", "firstlineno", "co_name"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_bc_instructions_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "instr_id",
                "code_unit_id",
                "instr_index",
                "offset",
                "opname",
                "opcode",
                "arg",
                "argval_str",
                "argrepr",
                "is_jump_target",
                "jump_target_offset",
                "starts_line",
                "pos_start_line",
                "pos_end_line",
                "pos_start_col",
                "pos_end_col",
            ],
            "derived": [
                {
                    "name": "code_unit_id",
                    "spec": "bc_code_unit_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "instr_id",
                    "spec": "bc_instr_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": [
                "qualpath",
                "co_name",
                "firstlineno",
                "instr_index",
                "offset",
                "opname",
                "opcode",
                "arg",
                "argval_str",
                "argrepr",
                "is_jump_target",
                "jump_target_offset",
                "starts_line",
                "pos_start_line",
                "pos_end_line",
                "pos_start_col",
                "pos_end_col",
            ],
            "row_extras": None,
            "template": "bytecode",
            "ordering_keys": None,
            "join_keys": ["code_unit_id", "instr_index", "offset"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_bc_exception_table_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "exc_entry_id",
                "code_unit_id",
                "exc_index",
                "start_offset",
                "end_offset",
                "target_offset",
                "depth",
                "lasti",
            ],
            "derived": [
                {
                    "name": "code_unit_id",
                    "spec": "bc_code_unit_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "exc_entry_id",
                    "spec": "bc_exc_entry_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": [
                "qualpath",
                "co_name",
                "firstlineno",
                "exc_index",
                "start_offset",
                "end_offset",
                "target_offset",
                "depth",
                "lasti",
            ],
            "row_extras": None,
            "template": "bytecode",
            "ordering_keys": None,
            "join_keys": [
                "code_unit_id",
                "exc_index",
                "start_offset",
                "end_offset",
                "target_offset",
            ],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_bc_blocks_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["block_id", "code_unit_id", "start_offset", "end_offset", "kind"],
            "derived": [
                {
                    "name": "code_unit_id",
                    "spec": "bc_code_unit_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "block_id",
                    "spec": "bc_block_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": [
                "qualpath",
                "co_name",
                "firstlineno",
                "start_offset",
                "end_offset",
                "kind",
            ],
            "row_extras": None,
            "template": "bytecode",
            "ordering_keys": None,
            "join_keys": ["code_unit_id", "start_offset", "end_offset"],
            "enabled_when": "feature_flag",
            "feature_flag": "include_cfg_derivations",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_bc_cfg_edges_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "edge_id",
                "code_unit_id",
                "src_block_id",
                "dst_block_id",
                "kind",
                "cond_instr_id",
                "exc_index",
            ],
            "derived": [
                {
                    "name": "code_unit_id",
                    "spec": "bc_code_unit_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "src_block_id",
                    "spec": "bc_src_block_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "dst_block_id",
                    "spec": "bc_dst_block_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "cond_instr_id",
                    "spec": "bc_cond_instr_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {"name": "edge_id", "spec": "bc_edge_id", "kind": "masked_hash", "required": None},
            ],
            "row_fields": [
                "qualpath",
                "co_name",
                "firstlineno",
                "src_block_start",
                "src_block_end",
                "dst_block_start",
                "dst_block_end",
                "kind",
                "edge_key",
                "cond_instr_index",
                "cond_instr_offset",
                "exc_index",
            ],
            "row_extras": None,
            "template": "bytecode",
            "ordering_keys": None,
            "join_keys": [
                "code_unit_id",
                "src_block_id",
                "dst_block_id",
                "kind",
                "edge_key",
                "exc_index",
            ],
            "enabled_when": "feature_flag",
            "feature_flag": "include_cfg_derivations",
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_bc_errors_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["error_type", "message"],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "bytecode",
            "ordering_keys": None,
            "join_keys": ["file_id", "message"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_sym_scopes_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "scope_id",
                "table_id",
                "scope_type",
                "scope_name",
                "lineno",
                "is_nested",
                "is_optimized",
                "has_children",
                "scope_role",
            ],
            "derived": [
                {
                    "name": "scope_id",
                    "spec": "sym_scope_id",
                    "kind": "masked_hash",
                    "required": None,
                }
            ],
            "row_fields": [
                "table_id",
                "scope_type",
                "scope_name",
                "lineno",
                "is_nested",
                "is_optimized",
                "has_children",
                "scope_role",
            ],
            "row_extras": None,
            "template": "symtable",
            "ordering_keys": None,
            "join_keys": ["file_id", "table_id"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_sym_symbols_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": [
                "symbol_row_id",
                "scope_id",
                "name",
                "is_referenced",
                "is_assigned",
                "is_imported",
                "is_annotated",
                "is_parameter",
                "is_global",
                "is_declared_global",
                "is_nonlocal",
                "is_local",
                "is_free",
                "is_namespace",
            ],
            "derived": [
                {
                    "name": "symbol_row_id",
                    "spec": "sym_symbol_row_id",
                    "kind": "masked_hash",
                    "required": None,
                }
            ],
            "row_fields": [
                "scope_table_id",
                "name",
                "is_referenced",
                "is_assigned",
                "is_imported",
                "is_annotated",
                "is_parameter",
                "is_global",
                "is_declared_global",
                "is_nonlocal",
                "is_local",
                "is_free",
                "is_namespace",
            ],
            "row_extras": None,
            "template": "symtable",
            "ordering_keys": None,
            "join_keys": ["file_id", "scope_id", "name"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_sym_scope_edges_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["edge_id", "parent_scope_id", "child_scope_id"],
            "derived": [
                {
                    "name": "edge_id",
                    "spec": "sym_scope_edge_id",
                    "kind": "masked_hash",
                    "required": None,
                }
            ],
            "row_fields": ["parent_table_id", "child_table_id"],
            "row_extras": None,
            "template": "symtable",
            "ordering_keys": None,
            "join_keys": ["file_id", "parent_scope_id", "child_scope_id"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_sym_namespace_edges_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["edge_id", "scope_id", "symbol_row_id", "child_scope_id"],
            "derived": [
                {
                    "name": "symbol_row_id",
                    "spec": "sym_ns_symbol_row_id",
                    "kind": "masked_hash",
                    "required": None,
                },
                {
                    "name": "edge_id",
                    "spec": "sym_ns_edge_id",
                    "kind": "masked_hash",
                    "required": None,
                },
            ],
            "row_fields": ["scope_table_id", "symbol_name", "child_table_id"],
            "row_extras": None,
            "template": "symtable",
            "ordering_keys": None,
            "join_keys": ["file_id", "scope_id", "symbol_row_id", "child_scope_id"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "py_sym_function_partitions_v1",
            "version": 1,
            "bundles": ["file_identity"],
            "fields": ["scope_id", "parameters", "locals", "globals", "nonlocals", "frees"],
            "derived": None,
            "row_fields": [
                "scope_table_id",
                "parameters",
                "locals",
                "globals",
                "nonlocals",
                "frees",
            ],
            "row_extras": None,
            "template": "symtable",
            "ordering_keys": None,
            "join_keys": ["file_id", "scope_id"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "scip_metadata_v1",
            "version": 1,
            "bundles": None,
            "fields": [
                "tool_name_dict",
                "tool_version_dict",
                "project_root_dict",
                "text_document_encoding_dict",
                "protocol_version_dict",
                "meta",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "scip",
            "ordering_keys": None,
            "join_keys": ["project_root_dict", "tool_name_dict", "tool_version_dict"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": None,
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "scip_documents_v1",
            "version": 1,
            "bundles": None,
            "fields": ["document_id", "path_dict", "language_dict", "position_encoding_dict"],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "scip",
            "ordering_keys": None,
            "join_keys": ["path_dict"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": "scip_documents",
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "scip_occurrences_v1",
            "version": 1,
            "bundles": ["scip_range_len", "scip_range_enc_len"],
            "fields": [
                "occurrence_id",
                "document_id",
                "path_dict",
                "symbol_dict",
                "symbol_roles",
                "syntax_kind_dict",
                "override_documentation",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "scip",
            "ordering_keys": None,
            "join_keys": ["document_id", "start_line", "start_char", "end_line", "end_char"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": "scip_occurrences",
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "scip_symbol_info_v1",
            "version": 1,
            "bundles": None,
            "fields": [
                "symbol_info_id",
                "symbol_dict",
                "display_name_dict",
                "kind_dict",
                "enclosing_symbol_dict",
                "documentation",
                "signature_documentation",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "scip",
            "ordering_keys": None,
            "join_keys": ["symbol_dict"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": "scip_symbol_info",
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "scip_symbol_relationships_v1",
            "version": 1,
            "bundles": None,
            "fields": [
                "relationship_id",
                "symbol_dict",
                "related_symbol_dict",
                "is_reference",
                "is_implementation",
                "is_type_definition",
                "is_definition",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "scip",
            "ordering_keys": None,
            "join_keys": [
                "symbol_dict",
                "related_symbol_dict",
                "is_reference",
                "is_implementation",
                "is_type_definition",
                "is_definition",
            ],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": "scip_symbol_relationships",
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "scip_external_symbol_info_v1",
            "version": 1,
            "bundles": None,
            "fields": [
                "symbol_info_id",
                "symbol_dict",
                "display_name_dict",
                "kind_dict",
                "enclosing_symbol_dict",
                "documentation",
                "signature_documentation",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "scip",
            "ordering_keys": None,
            "join_keys": ["symbol_dict"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": "scip_external_symbol_info",
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
        {
            "name": "scip_diagnostics_v1",
            "version": 1,
            "bundles": ["scip_range"],
            "fields": [
                "diagnostic_id",
                "document_id",
                "path_dict",
                "severity_dict",
                "code_dict",
                "message",
                "source_dict",
                "tags",
            ],
            "derived": None,
            "row_fields": None,
            "row_extras": None,
            "template": "scip",
            "ordering_keys": None,
            "join_keys": ["document_id", "start_line", "start_char", "end_line", "end_char"],
            "enabled_when": None,
            "feature_flag": None,
            "postprocess": "scip_diagnostics",
            "metadata_extra": None,
            "evidence_required_columns": None,
        },
)

_TEMPLATE_ROW_RECORDS = expand_dataset_templates(DATASET_TEMPLATE_SPECS)

EXTRACT_DATASET_TABLE = extract_dataset_table_from_rows(
    (*DATASET_ROW_RECORDS, *_TEMPLATE_ROW_RECORDS)
)

DATASET_ROW_SPECS: tuple[ExtractDatasetRowSpec, ...] = dataset_rows_from_table(
    EXTRACT_DATASET_TABLE
)


__all__ = ["DATASET_ROW_SPECS", "EXTRACT_DATASET_TABLE"]
