from collections.abc import Iterator, Mapping, Sequence
from types import TracebackType
from typing import Self

class Array:
    null_count: int
    type: DataType

    def field(self, index: int | str) -> Array: ...
    def to_pylist(self) -> list[object]: ...
    def __iter__(self) -> Iterator[object]: ...
    def __len__(self) -> int: ...

class ChunkedArray(Array):
    def combine_chunks(self) -> Array: ...

class Scalar:
    type: DataType
    def as_py(self) -> object: ...

class DataType: ...

class Field:
    name: str
    type: DataType
    metadata: Mapping[bytes, bytes] | None
    nullable: bool

class Schema:
    names: list[str]
    metadata: Mapping[bytes, bytes] | None

    def with_metadata(self, metadata: Mapping[bytes, bytes]) -> Schema: ...
    def field(self, name_or_index: str | int) -> Field: ...
    def get_field_index(self, name: str) -> int: ...
    def __iter__(self) -> Iterator[Field]: ...

class RecordBatchReader:
    schema: Schema
    def read_all(self) -> Table: ...

class NativeFile:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

class Table:
    num_rows: int
    column_names: list[str]
    schema: Schema

    @staticmethod
    def from_pylist(
        data: Sequence[Mapping[str, object]], schema: Schema | None = None
    ) -> Table: ...
    @staticmethod
    def from_arrays(
        arrays: Sequence[Array | ChunkedArray],
        schema: Schema | None = None,
        names: Sequence[str] | None = None,
    ) -> Table: ...
    def append_column(self, name: str, data: Array | ChunkedArray) -> Table: ...
    def drop(self, columns: Sequence[str]) -> Table: ...
    def rename_columns(self, names: Sequence[str]) -> Table: ...
    def to_pylist(self) -> list[dict[str, object]]: ...
    def filter(self, mask: Array) -> Table: ...
    def take(self, indices: Array) -> Table: ...
    def group_by(self, keys: Sequence[str], *, use_threads: bool = True) -> TableGroupBy: ...
    def join(
        self,
        right: Table,
        keys: Sequence[str],
        right_keys: Sequence[str] | None = None,
        join_type: str = "left outer",
        left_suffix: str | None = None,
        right_suffix: str | None = None,
        coalesce_keys: bool = True,
        use_threads: bool = True,
        filter_expression: object | None = None,
    ) -> Table: ...
    def select(self, names: Sequence[str]) -> Table: ...
    def set_column(self, i: int, name: str, data: Array | ChunkedArray) -> Table: ...
    def to_reader(self) -> RecordBatchReader: ...
    def __getitem__(self, key: str) -> ChunkedArray: ...

class TableGroupBy:
    def aggregate(self, aggs: Sequence[tuple[str, str]]) -> Table: ...

class ArrowError(Exception): ...
class ArrowInvalidError(ArrowError): ...
class ArrowTypeError(TypeError): ...

ArrowInvalid = ArrowInvalidError

def array(
    data: Sequence[object],
    *,
    data_type: DataType | None = None,
    **kwargs: object,
) -> Array: ...
def scalar(
    value: object,
    *,
    data_type: DataType | None = None,
    **kwargs: object,
) -> Scalar: ...
def schema(fields: Sequence[Field | tuple[str, DataType]]) -> Schema: ...
def field(name: str, data_type: DataType, **kwargs: object) -> Field: ...
def nulls(size: int, *, data_type: DataType | None = None, **kwargs: object) -> Array: ...
def table(
    data: Mapping[str, Sequence[object] | Array] | Sequence[Array],
    schema: Schema | None = None,
    names: Sequence[str] | None = None,
) -> Table: ...
def concat_tables(tables: Sequence[Table], promote: bool = False) -> Table: ...
def unify_schemas(
    schemas: Sequence[Schema],
    *,
    promote_options: object | None = None,
) -> Schema: ...
def set_cpu_count(count: int) -> None: ...
def set_io_thread_count(count: int) -> None: ...
def OSFile(path: str, mode: str) -> NativeFile: ...
def memory_map(path: str, mode: str) -> NativeFile: ...
def string() -> DataType: ...
def int64() -> DataType: ...
def int32() -> DataType: ...
def float32() -> DataType: ...
def float64() -> DataType: ...
def bool_() -> DataType: ...
def binary() -> DataType: ...
def list_(value_type: DataType, *, list_size: int | None = None) -> DataType: ...
def struct(fields: Sequence[Field | tuple[str, DataType]]) -> DataType: ...
def __getattr__(name: str) -> object: ...

class StructArray(Array):
    @staticmethod
    def from_arrays(
        arrays: Sequence[Array | ChunkedArray],
        *,
        names: Sequence[str],
        mask: Array | None = None,
    ) -> StructArray: ...

class ListArray(Array):
    @staticmethod
    def from_arrays(
        offsets: Array | ChunkedArray,
        values: Array | ChunkedArray,
    ) -> ListArray: ...
