from __future__ import annotations

from collections.abc import Sequence


class Expression: ...


class Array: ...


class ChunkedArray(Array): ...


class Scalar: ...


def field(name: str) -> Expression: ...

def scalar(value: object) -> Expression: ...

def cast(expr: Expression | Array | ChunkedArray | Scalar, target_type: object, *, safe: bool = True) -> Array: ...

def coalesce(*args: Expression) -> Expression: ...

def is_null(expr: Expression | Array | ChunkedArray) -> Array: ...

def is_valid(expr: Expression | Array | ChunkedArray) -> Array: ...

def invert(values: Array) -> Array: ...

def value_counts(values: Array | ChunkedArray) -> Array: ...

def sort_indices(table: object, *, sort_keys: Sequence[tuple[str, str]]) -> Array: ...

def equal(left: Array | ChunkedArray | Scalar, right: Array | ChunkedArray | Scalar) -> Array: ...

def fill_null(values: Array, replacement: bool) -> Array: ...

def list_parent_indices(values: Array | ChunkedArray) -> Array: ...

def list_flatten(values: Array | ChunkedArray) -> Array: ...

def take(values: Array | ChunkedArray, indices: Array) -> Array: ...
