"""DataFusion-native nested schemas for canonical datasets (backward-compat re-export shim).

Canonical definitions have moved to:
- ``datafusion_engine.schema.extraction_schemas`` - Extraction evidence table schemas
- ``datafusion_engine.schema.nested_views`` - Nested view specification and registration
- ``datafusion_engine.schema.observability_schemas`` - Pipeline observability schemas

This module re-exports all public symbols for backward compatibility.
Existing callers do not need to update their imports.

Schema drift and evolution:
Schemas registered in this module can leverage scan-time schema adapters when
the runtime profile enables ``enable_schema_evolution_adapter=True``. Schema
adapters normalize physical batches at the TableProvider boundary, handling
column reordering, type coercion, and missing/extra columns during physical
plan execution. This eliminates the need for downstream drift normalization
transforms.
"""

from __future__ import annotations

# Re-export constants from arrow_utils used by downstream callers
# (e.g., relspec/contracts.py imports these from this module).
from arrow_utils.core.schema_constants import (
    SCHEMA_META_NAME,
    SCHEMA_META_VERSION,
)

# ---------------------------------------------------------------------------
# Extraction schemas re-exports
# ---------------------------------------------------------------------------
from datafusion_engine.schema.extraction_schemas import (
    AST_CORE_VIEW_NAMES,
    AST_FILES_SCHEMA,
    AST_OPTIONAL_VIEW_NAMES,
    AST_VIEW_NAMES,
    BYTECODE_FILES_SCHEMA,
    BYTECODE_VIEW_NAMES,
    CST_VIEW_NAMES,
    DIAG_DETAIL_STRUCT,
    DIAG_DETAILS_TYPE,
    DIAG_TAGS_TYPE,
    LIBCST_FILES_SCHEMA,
    REL_CALLSITE_SYMBOL_SCHEMA,
    REL_DEF_SYMBOL_SCHEMA,
    REL_IMPORT_SYMBOL_SCHEMA,
    REL_NAME_SYMBOL_SCHEMA,
    RELATIONSHIP_SCHEMA_BY_NAME,
    REPO_FILES_SCHEMA,
    SCIP_DIAGNOSTICS_SCHEMA,
    SCIP_DOCUMENT_SYMBOLS_SCHEMA,
    SCIP_DOCUMENT_TEXTS_SCHEMA,
    SCIP_DOCUMENTS_SCHEMA,
    SCIP_EXTERNAL_SYMBOL_INFORMATION_SCHEMA,
    SCIP_INDEX_SCHEMA,
    SCIP_INDEX_STATS_SCHEMA,
    SCIP_METADATA_SCHEMA,
    SCIP_OCCURRENCES_NORM_SCHEMA,
    SCIP_OCCURRENCES_SCHEMA,
    SCIP_SIGNATURE_OCCURRENCES_SCHEMA,
    SCIP_SYMBOL_INFORMATION_SCHEMA,
    SCIP_SYMBOL_RELATIONSHIPS_SCHEMA,
    SCIP_VIEW_NAMES,
    SYMTABLE_FILES_SCHEMA,
    SYMTABLE_VIEW_NAMES,
    TREE_SITTER_CHECK_VIEWS,
    TREE_SITTER_FILES_SCHEMA,
    TREE_SITTER_VIEW_NAMES,
    _resolve_nested_row_schema_authority,
    base_extract_schema_registry,
    default_attrs_value,
    extract_base_schema_for,
    extract_base_schema_names,
    extract_nested_schema_for,
    extract_schema_contract_for,
    extract_schema_for,
    relationship_schema_for,
    relationship_schema_names,
    relationship_schema_registry,
)

# ---------------------------------------------------------------------------
# Nested views re-exports
# ---------------------------------------------------------------------------
from datafusion_engine.schema.nested_views import (
    NESTED_DATASET_INDEX,
    datasets_for_path,
    extract_datasets_for_path,
    extract_nested_context_for,
    extract_nested_dataset_names,
    extract_nested_path_for,
    extract_nested_role_for,
    extract_nested_schema_names,
    extract_nested_spec_for,
    identity_fields_for,
    is_extract_intrinsic_nested_dataset,
    is_extract_nested_dataset,
    is_intrinsic_nested_dataset,
    is_nested_dataset,
    nested_base_df,
    nested_context_for,
    nested_dataset_names,
    nested_dataset_registry,
    nested_path_for,
    nested_role_for,
    nested_schema_names,
    nested_view_spec,
    nested_view_specs,
    root_identity_registry,
    struct_for_path,
    validate_nested_types,
)

# ---------------------------------------------------------------------------
# Observability schemas re-exports
# ---------------------------------------------------------------------------
from datafusion_engine.schema.observability_schemas import (
    DATAFUSION_PIPELINE_EVENTS_V2_SCHEMA,
    DATAFUSION_PLAN_ARTIFACTS_SCHEMA,
    DATAFUSION_RUNS_SCHEMA,
    DATAFUSION_SQL_INGEST_SCHEMA,
    DATAFUSION_VIEW_ARTIFACTS_SCHEMA,
    PIPELINE_PLAN_DRIFT_SCHEMA,
    PIPELINE_TASK_EXPANSION_SCHEMA,
    PIPELINE_TASK_GROUPING_SCHEMA,
    PIPELINE_TASK_SUBMISSION_SCHEMA,
    _semantic_validation_tables,
    missing_schema_names,
    registered_table_names,
    schema_contract_for_table,
    validate_ast_views,
    validate_bytecode_views,
    validate_cst_views,
    validate_required_bytecode_functions,
    validate_required_cst_functions,
    validate_required_engine_functions,
    validate_required_symtable_functions,
    validate_schema_metadata,
    validate_scip_views,
    validate_semantic_types,
    validate_symtable_views,
    validate_ts_views,
    validate_udf_info_schema_parity,
)

__all__ = [
    "AST_CORE_VIEW_NAMES",
    "AST_FILES_SCHEMA",
    "AST_OPTIONAL_VIEW_NAMES",
    "AST_VIEW_NAMES",
    "BYTECODE_FILES_SCHEMA",
    "BYTECODE_VIEW_NAMES",
    "CST_VIEW_NAMES",
    "DATAFUSION_PIPELINE_EVENTS_V2_SCHEMA",
    "DATAFUSION_PLAN_ARTIFACTS_SCHEMA",
    "DATAFUSION_RUNS_SCHEMA",
    "DATAFUSION_SQL_INGEST_SCHEMA",
    "DATAFUSION_VIEW_ARTIFACTS_SCHEMA",
    "DIAG_DETAILS_TYPE",
    "DIAG_DETAIL_STRUCT",
    "DIAG_TAGS_TYPE",
    "LIBCST_FILES_SCHEMA",
    "NESTED_DATASET_INDEX",
    "PIPELINE_PLAN_DRIFT_SCHEMA",
    "PIPELINE_TASK_EXPANSION_SCHEMA",
    "PIPELINE_TASK_GROUPING_SCHEMA",
    "PIPELINE_TASK_SUBMISSION_SCHEMA",
    "RELATIONSHIP_SCHEMA_BY_NAME",
    "REL_CALLSITE_SYMBOL_SCHEMA",
    "REL_DEF_SYMBOL_SCHEMA",
    "REL_IMPORT_SYMBOL_SCHEMA",
    "REL_NAME_SYMBOL_SCHEMA",
    "REPO_FILES_SCHEMA",
    "SCHEMA_META_NAME",
    "SCHEMA_META_VERSION",
    "SCIP_DIAGNOSTICS_SCHEMA",
    "SCIP_DOCUMENTS_SCHEMA",
    "SCIP_DOCUMENT_SYMBOLS_SCHEMA",
    "SCIP_DOCUMENT_TEXTS_SCHEMA",
    "SCIP_EXTERNAL_SYMBOL_INFORMATION_SCHEMA",
    "SCIP_INDEX_SCHEMA",
    "SCIP_INDEX_STATS_SCHEMA",
    "SCIP_METADATA_SCHEMA",
    "SCIP_OCCURRENCES_NORM_SCHEMA",
    "SCIP_OCCURRENCES_SCHEMA",
    "SCIP_SIGNATURE_OCCURRENCES_SCHEMA",
    "SCIP_SYMBOL_INFORMATION_SCHEMA",
    "SCIP_SYMBOL_RELATIONSHIPS_SCHEMA",
    "SCIP_VIEW_NAMES",
    "SYMTABLE_FILES_SCHEMA",
    "SYMTABLE_VIEW_NAMES",
    "TREE_SITTER_CHECK_VIEWS",
    "TREE_SITTER_FILES_SCHEMA",
    "TREE_SITTER_VIEW_NAMES",
    # Private symbols re-exported for test access via module attribute
    "_resolve_nested_row_schema_authority",
    "_semantic_validation_tables",
    "base_extract_schema_registry",
    "datasets_for_path",
    "default_attrs_value",
    "extract_base_schema_for",
    "extract_base_schema_names",
    "extract_datasets_for_path",
    "extract_nested_context_for",
    "extract_nested_dataset_names",
    "extract_nested_path_for",
    "extract_nested_role_for",
    "extract_nested_schema_for",
    "extract_nested_schema_names",
    "extract_nested_spec_for",
    "extract_schema_contract_for",
    "extract_schema_for",
    "identity_fields_for",
    "is_extract_intrinsic_nested_dataset",
    "is_extract_nested_dataset",
    "is_intrinsic_nested_dataset",
    "is_nested_dataset",
    "missing_schema_names",
    "nested_base_df",
    "nested_context_for",
    "nested_dataset_names",
    "nested_dataset_registry",
    "nested_path_for",
    "nested_role_for",
    "nested_schema_names",
    "nested_view_spec",
    "nested_view_specs",
    "registered_table_names",
    "relationship_schema_for",
    "relationship_schema_names",
    "relationship_schema_registry",
    "root_identity_registry",
    "schema_contract_for_table",
    "struct_for_path",
    "validate_ast_views",
    "validate_bytecode_views",
    "validate_cst_views",
    "validate_nested_types",
    "validate_required_bytecode_functions",
    "validate_required_cst_functions",
    "validate_required_engine_functions",
    "validate_required_symtable_functions",
    "validate_schema_metadata",
    "validate_scip_views",
    "validate_semantic_types",
    "validate_symtable_views",
    "validate_ts_views",
    "validate_udf_info_schema_parity",
]
