"""Schema specification models and adapters."""

from __future__ import annotations

from schema_spec.specs import (
    DICT_STRING,
    PROVENANCE_COLS,
    PROVENANCE_SOURCE_FIELDS,
    SCHEMA_META_NAME,
    SCHEMA_META_VERSION,
    ArrowFieldSpec,
    FieldBundle,
    NestedFieldSpec,
    TableSchemaSpec,
)
from schema_spec.system import (
    GLOBAL_SCHEMA_REGISTRY,
    ContractCatalogSpec,
    ContractSpec,
    DatasetSpec,
    DedupeSpecSpec,
    PanderaValidationOptions,
    SchemaRegistry,
    SortKeySpec,
    TableSpecConstraints,
    VirtualFieldSpec,
    dataset_spec_from_contract,
    dataset_spec_from_schema,
    make_contract_spec,
    make_dataset_spec,
    make_table_spec,
    table_spec_from_schema,
    table_spec_to_pandera,
    validate_arrow_table,
)

__all__ = [
    "DICT_STRING",
    "GLOBAL_SCHEMA_REGISTRY",
    "PROVENANCE_COLS",
    "PROVENANCE_SOURCE_FIELDS",
    "SCHEMA_META_NAME",
    "SCHEMA_META_VERSION",
    "ArrowFieldSpec",
    "ContractCatalogSpec",
    "ContractSpec",
    "DatasetSpec",
    "DedupeSpecSpec",
    "FieldBundle",
    "NestedFieldSpec",
    "PanderaValidationOptions",
    "SchemaRegistry",
    "SortKeySpec",
    "TableSchemaSpec",
    "TableSpecConstraints",
    "VirtualFieldSpec",
    "dataset_spec_from_contract",
    "dataset_spec_from_schema",
    "make_contract_spec",
    "make_dataset_spec",
    "make_table_spec",
    "table_spec_from_schema",
    "table_spec_to_pandera",
    "validate_arrow_table",
]
