"""Schema specification models and adapters."""

from __future__ import annotations

from schema_spec.specs import (
    DICT_STRING,
    ENCODING_DICTIONARY,
    ENCODING_META,
    KEY_FIELDS_META,
    PROVENANCE_COLS,
    PROVENANCE_SOURCE_FIELDS,
    REQUIRED_NON_NULL_META,
    SCHEMA_META_NAME,
    SCHEMA_META_VERSION,
    ArrowFieldSpec,
    DerivedFieldSpec,
    FieldBundle,
    NestedFieldSpec,
    TableSchemaSpec,
)
from schema_spec.system import (
    GLOBAL_SCHEMA_REGISTRY,
    ArrowValidationOptions,
    ContractCatalogSpec,
    ContractSpec,
    DatasetOpenSpec,
    DatasetSpec,
    DedupeSpecSpec,
    SchemaRegistry,
    SortKeySpec,
    TableSpecConstraints,
    ValidationPlans,
    VirtualFieldSpec,
    dataset_spec_from_contract,
    dataset_spec_from_dataset,
    dataset_spec_from_path,
    dataset_spec_from_schema,
    make_contract_spec,
    make_dataset_spec,
    make_table_spec,
    table_spec_from_schema,
    validate_arrow_table,
)

__all__ = [
    "DICT_STRING",
    "ENCODING_DICTIONARY",
    "ENCODING_META",
    "GLOBAL_SCHEMA_REGISTRY",
    "KEY_FIELDS_META",
    "PROVENANCE_COLS",
    "PROVENANCE_SOURCE_FIELDS",
    "REQUIRED_NON_NULL_META",
    "SCHEMA_META_NAME",
    "SCHEMA_META_VERSION",
    "ArrowFieldSpec",
    "ArrowValidationOptions",
    "ContractCatalogSpec",
    "ContractSpec",
    "DatasetOpenSpec",
    "DatasetSpec",
    "DedupeSpecSpec",
    "DerivedFieldSpec",
    "FieldBundle",
    "NestedFieldSpec",
    "SchemaRegistry",
    "SortKeySpec",
    "TableSchemaSpec",
    "TableSpecConstraints",
    "ValidationPlans",
    "VirtualFieldSpec",
    "dataset_spec_from_contract",
    "dataset_spec_from_dataset",
    "dataset_spec_from_path",
    "dataset_spec_from_schema",
    "make_contract_spec",
    "make_dataset_spec",
    "make_table_spec",
    "table_spec_from_schema",
    "validate_arrow_table",
]
