"""Schema specification models and adapters."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from arrowdsl.spec.tables.schema import (
        CONTRACT_SPEC_SCHEMA,
        FIELD_SPEC_SCHEMA,
        TABLE_CONSTRAINTS_SCHEMA,
        SchemaSpecTables,
        contract_spec_table,
        contract_specs_from_table,
        dataset_specs_from_tables,
        field_spec_table,
        schema_spec_tables_from_dataset_specs,
        table_constraints_table,
        table_specs_from_tables,
    )
    from schema_spec.specs import (
        DICT_STRING,
        ENCODING_DICTIONARY,
        ENCODING_META,
        KEY_FIELDS_META,
        PROVENANCE_COLS,
        PROVENANCE_SOURCE_FIELDS,
        REQUIRED_NON_NULL_META,
        SCHEMA_META_NAME,
        SCHEMA_META_VERSION,
        ArrowFieldSpec,
        DerivedFieldSpec,
        FieldBundle,
        NestedFieldSpec,
        TableSchemaSpec,
        call_span_bundle,
        dict_field,
        file_identity_bundle,
        list_view_type,
        provenance_bundle,
        schema_metadata,
        schema_metadata_for_spec,
        scip_range_bundle,
        span_bundle,
    )
    from schema_spec.system import (
        GLOBAL_SCHEMA_REGISTRY,
        ArrowValidationOptions,
        ContractCatalogSpec,
        ContractSpec,
        DatasetOpenSpec,
        DatasetSpec,
        DedupeSpecSpec,
        DeltaScanOptions,
        DeltaSchemaPolicy,
        DeltaWritePolicy,
        SchemaRegistry,
        SortKeySpec,
        TableSpecConstraints,
        ValidationPlans,
        VirtualFieldSpec,
        contract_catalog_spec_from_tables,
        dataset_spec_from_contract,
        dataset_spec_from_dataset,
        dataset_spec_from_path,
        dataset_spec_from_schema,
        ddl_fingerprint_from_schema,
        make_contract_spec,
        make_dataset_spec,
        make_table_spec,
        table_spec_from_schema,
        validate_arrow_table,
    )

_EXPORT_MAP: dict[str, tuple[str, str]] = {
    "CONTRACT_SPEC_SCHEMA": ("arrowdsl.spec.tables.schema", "CONTRACT_SPEC_SCHEMA"),
    "DICT_STRING": ("schema_spec.specs", "DICT_STRING"),
    "ENCODING_DICTIONARY": ("schema_spec.specs", "ENCODING_DICTIONARY"),
    "ENCODING_META": ("schema_spec.specs", "ENCODING_META"),
    "FIELD_SPEC_SCHEMA": ("arrowdsl.spec.tables.schema", "FIELD_SPEC_SCHEMA"),
    "GLOBAL_SCHEMA_REGISTRY": ("schema_spec.system", "GLOBAL_SCHEMA_REGISTRY"),
    "KEY_FIELDS_META": ("schema_spec.specs", "KEY_FIELDS_META"),
    "PROVENANCE_COLS": ("schema_spec.specs", "PROVENANCE_COLS"),
    "PROVENANCE_SOURCE_FIELDS": ("schema_spec.specs", "PROVENANCE_SOURCE_FIELDS"),
    "REQUIRED_NON_NULL_META": ("schema_spec.specs", "REQUIRED_NON_NULL_META"),
    "SCHEMA_META_NAME": ("schema_spec.specs", "SCHEMA_META_NAME"),
    "SCHEMA_META_VERSION": ("schema_spec.specs", "SCHEMA_META_VERSION"),
    "TABLE_CONSTRAINTS_SCHEMA": ("arrowdsl.spec.tables.schema", "TABLE_CONSTRAINTS_SCHEMA"),
    "ArrowFieldSpec": ("schema_spec.specs", "ArrowFieldSpec"),
    "ArrowValidationOptions": ("schema_spec.system", "ArrowValidationOptions"),
    "ContractCatalogSpec": ("schema_spec.system", "ContractCatalogSpec"),
    "ContractSpec": ("schema_spec.system", "ContractSpec"),
    "DatasetOpenSpec": ("schema_spec.system", "DatasetOpenSpec"),
    "DatasetSpec": ("schema_spec.system", "DatasetSpec"),
    "DedupeSpecSpec": ("schema_spec.system", "DedupeSpecSpec"),
    "DeltaScanOptions": ("schema_spec.system", "DeltaScanOptions"),
    "DeltaSchemaPolicy": ("schema_spec.system", "DeltaSchemaPolicy"),
    "DeltaWritePolicy": ("schema_spec.system", "DeltaWritePolicy"),
    "DerivedFieldSpec": ("schema_spec.specs", "DerivedFieldSpec"),
    "FieldBundle": ("schema_spec.specs", "FieldBundle"),
    "NestedFieldSpec": ("schema_spec.specs", "NestedFieldSpec"),
    "SchemaRegistry": ("schema_spec.system", "SchemaRegistry"),
    "SchemaSpecTables": ("arrowdsl.spec.tables.schema", "SchemaSpecTables"),
    "SortKeySpec": ("schema_spec.system", "SortKeySpec"),
    "TableSchemaSpec": ("schema_spec.specs", "TableSchemaSpec"),
    "TableSpecConstraints": ("schema_spec.system", "TableSpecConstraints"),
    "ValidationPlans": ("schema_spec.system", "ValidationPlans"),
    "VirtualFieldSpec": ("schema_spec.system", "VirtualFieldSpec"),
    "call_span_bundle": ("schema_spec.specs", "call_span_bundle"),
    "contract_catalog_spec_from_tables": (
        "schema_spec.system",
        "contract_catalog_spec_from_tables",
    ),
    "contract_spec_table": ("arrowdsl.spec.tables.schema", "contract_spec_table"),
    "contract_specs_from_table": ("arrowdsl.spec.tables.schema", "contract_specs_from_table"),
    "dataset_spec_from_contract": ("schema_spec.system", "dataset_spec_from_contract"),
    "dataset_spec_from_dataset": ("schema_spec.system", "dataset_spec_from_dataset"),
    "dataset_spec_from_path": ("schema_spec.system", "dataset_spec_from_path"),
    "dataset_spec_from_schema": ("schema_spec.system", "dataset_spec_from_schema"),
    "dataset_specs_from_tables": ("arrowdsl.spec.tables.schema", "dataset_specs_from_tables"),
    "ddl_fingerprint_from_schema": ("schema_spec.system", "ddl_fingerprint_from_schema"),
    "dict_field": ("schema_spec.specs", "dict_field"),
    "field_spec_table": ("arrowdsl.spec.tables.schema", "field_spec_table"),
    "file_identity_bundle": ("schema_spec.specs", "file_identity_bundle"),
    "list_view_type": ("schema_spec.specs", "list_view_type"),
    "make_contract_spec": ("schema_spec.system", "make_contract_spec"),
    "make_dataset_spec": ("schema_spec.system", "make_dataset_spec"),
    "make_table_spec": ("schema_spec.system", "make_table_spec"),
    "provenance_bundle": ("schema_spec.specs", "provenance_bundle"),
    "schema_metadata": ("schema_spec.specs", "schema_metadata"),
    "schema_metadata_for_spec": ("schema_spec.specs", "schema_metadata_for_spec"),
    "schema_spec_tables_from_dataset_specs": (
        "arrowdsl.spec.tables.schema",
        "schema_spec_tables_from_dataset_specs",
    ),
    "scip_range_bundle": ("schema_spec.specs", "scip_range_bundle"),
    "span_bundle": ("schema_spec.specs", "span_bundle"),
    "table_constraints_table": ("arrowdsl.spec.tables.schema", "table_constraints_table"),
    "table_spec_from_schema": ("schema_spec.system", "table_spec_from_schema"),
    "table_specs_from_tables": ("arrowdsl.spec.tables.schema", "table_specs_from_tables"),
    "validate_arrow_table": ("schema_spec.system", "validate_arrow_table"),
}


def __getattr__(name: str) -> object:
    target = _EXPORT_MAP.get(name)
    if target is None:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)
    module_path, attr_name = target
    module = importlib.import_module(module_path)
    return getattr(module, attr_name)


def __dir__() -> list[str]:
    return sorted(list(globals()) + list(_EXPORT_MAP))


__all__ = [
    "CONTRACT_SPEC_SCHEMA",
    "DICT_STRING",
    "ENCODING_DICTIONARY",
    "ENCODING_META",
    "FIELD_SPEC_SCHEMA",
    "GLOBAL_SCHEMA_REGISTRY",
    "KEY_FIELDS_META",
    "PROVENANCE_COLS",
    "PROVENANCE_SOURCE_FIELDS",
    "REQUIRED_NON_NULL_META",
    "SCHEMA_META_NAME",
    "SCHEMA_META_VERSION",
    "TABLE_CONSTRAINTS_SCHEMA",
    "ArrowFieldSpec",
    "ArrowValidationOptions",
    "ContractCatalogSpec",
    "ContractSpec",
    "DatasetOpenSpec",
    "DatasetSpec",
    "DedupeSpecSpec",
    "DeltaScanOptions",
    "DeltaSchemaPolicy",
    "DeltaWritePolicy",
    "DerivedFieldSpec",
    "FieldBundle",
    "NestedFieldSpec",
    "SchemaRegistry",
    "SchemaSpecTables",
    "SortKeySpec",
    "TableSchemaSpec",
    "TableSpecConstraints",
    "ValidationPlans",
    "VirtualFieldSpec",
    "call_span_bundle",
    "contract_catalog_spec_from_tables",
    "contract_spec_table",
    "contract_specs_from_table",
    "dataset_spec_from_contract",
    "dataset_spec_from_dataset",
    "dataset_spec_from_path",
    "dataset_spec_from_schema",
    "dataset_specs_from_tables",
    "ddl_fingerprint_from_schema",
    "dict_field",
    "field_spec_table",
    "file_identity_bundle",
    "list_view_type",
    "make_contract_spec",
    "make_dataset_spec",
    "make_table_spec",
    "provenance_bundle",
    "schema_metadata",
    "schema_metadata_for_spec",
    "schema_spec_tables_from_dataset_specs",
    "scip_range_bundle",
    "span_bundle",
    "table_constraints_table",
    "table_spec_from_schema",
    "table_specs_from_tables",
    "validate_arrow_table",
]
