"""Registry of diagnostic semantic datasets."""

from __future__ import annotations

from typing import Final

from semantics.catalog.dataset_registry import DatasetRegistrySpec
from semantics.catalog.dataset_rows import SEMANTIC_SCHEMA_VERSION

DIAGNOSTIC_DATASETS: Final[tuple[DatasetRegistrySpec, ...]] = (
    DatasetRegistrySpec(
        name="relationship_quality_metrics_v1",
        version=SEMANTIC_SCHEMA_VERSION,
        bundles=(),
        fields=(
            "relationship_name",
            "total_edges",
            "distinct_sources",
            "distinct_targets",
            "avg_confidence",
            "min_confidence",
            "max_confidence",
            "low_confidence_edges",
            "avg_score",
            "min_score",
            "max_score",
        ),
        category="diagnostic",
        supports_cdf=False,
        merge_keys=("relationship_name",),
        join_keys=("relationship_name",),
        template="relationship_quality_metrics",
        view_builder="relationship_quality_metrics_df_builder",
        register_view=True,
    ),
    DatasetRegistrySpec(
        name="relationship_ambiguity_report_v1",
        version=SEMANTIC_SCHEMA_VERSION,
        bundles=(),
        fields=(
            "relationship_name",
            "total_sources",
            "ambiguous_sources",
            "max_candidates",
            "avg_candidates",
            "ambiguity_rate",
        ),
        category="diagnostic",
        supports_cdf=False,
        merge_keys=("relationship_name",),
        join_keys=("relationship_name",),
        template="relationship_ambiguity_report",
        view_builder="relationship_ambiguity_report_df_builder",
        register_view=True,
    ),
    DatasetRegistrySpec(
        name="relationship_candidates_v1",
        version=SEMANTIC_SCHEMA_VERSION,
        bundles=(),
        fields=(
            "relationship_name",
            "src",
            "dst",
            "path",
            "bstart",
            "bend",
            "confidence",
            "score",
            "ambiguity_group_id",
            "task_name",
            "task_priority",
            "edge_kind",
        ),
        category="diagnostic",
        supports_cdf=False,
        merge_keys=("relationship_name", "src", "dst"),
        join_keys=("relationship_name", "src", "dst"),
        template="relationship_candidates",
        view_builder="relationship_candidates_df_builder",
        register_view=True,
    ),
    DatasetRegistrySpec(
        name="relationship_decisions_v1",
        version=SEMANTIC_SCHEMA_VERSION,
        bundles=(),
        fields=(
            "relationship_name",
            "src",
            "dst",
            "path",
            "bstart",
            "bend",
            "confidence",
            "score",
            "ambiguity_group_id",
            "task_name",
            "task_priority",
            "edge_kind",
        ),
        category="diagnostic",
        supports_cdf=False,
        merge_keys=("relationship_name", "src", "dst"),
        join_keys=("relationship_name", "src", "dst"),
        template="relationship_decisions",
        view_builder="relationship_decisions_df_builder",
        register_view=True,
    ),
    DatasetRegistrySpec(
        name="schema_anomalies_v1",
        version=SEMANTIC_SCHEMA_VERSION,
        bundles=(),
        fields=(
            "view_name",
            "violation_type",
            "column_name",
            "detail",
        ),
        category="diagnostic",
        supports_cdf=False,
        merge_keys=("view_name", "violation_type", "column_name"),
        join_keys=("view_name", "violation_type", "column_name"),
        template="schema_anomalies",
        view_builder="schema_anomalies_df_builder",
        register_view=True,
    ),
    DatasetRegistrySpec(
        name="file_coverage_report_v1",
        version=SEMANTIC_SCHEMA_VERSION,
        bundles=(),
        fields=(
            "file_id",
            "has_cst",
            "has_tree_sitter",
            "has_scip",
            "extraction_count",
        ),
        category="diagnostic",
        supports_cdf=False,
        merge_keys=("file_id",),
        join_keys=("file_id",),
        template="file_coverage_report",
        view_builder="file_coverage_report_df_builder",
        register_view=True,
    ),
)

__all__ = ["DIAGNOSTIC_DATASETS"]
