"""Registry of normalize layer datasets."""

from __future__ import annotations

from typing import Final

from semantics.catalog.dataset_registry import DatasetRegistrySpec

NORMALIZE_SCHEMA_VERSION: Final[int] = 1

NORMALIZE_DATASETS: Final[tuple[DatasetRegistrySpec, ...]] = (
    DatasetRegistrySpec(
        name="normalize_evidence",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=(
            "span_id",
            "evidence_family",
            "source",
            "role",
            "confidence",
            "ambiguity_group_id",
            "task_name",
        ),
        category="semantic",
        supports_cdf=True,
        join_keys=("span_id", "task_name"),
        template="normalize_evidence",
        register_view=False,
    ),
    DatasetRegistrySpec(
        name="type_exprs_norm",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=(
            "type_expr_id",
            "owner_def_id",
            "param_name",
            "expr_kind",
            "expr_role",
            "expr_text",
            "type_repr",
            "type_id",
        ),
        category="semantic",
        supports_cdf=True,
        join_keys=("type_expr_id",),
        template="normalize_cst",
        view_builder="type_exprs_df_builder",
    ),
    DatasetRegistrySpec(
        name="type_nodes",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=(),
        fields=("type_id", "type_repr", "type_form", "origin"),
        category="semantic",
        supports_cdf=True,
        join_keys=("type_id",),
        template="normalize_type",
        view_builder="type_nodes_df_builder",
    ),
    DatasetRegistrySpec(
        name="py_bc_blocks_norm",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=("block_id", "code_unit_id", "start_offset", "end_offset", "kind"),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("code_unit_id", "block_id"),
        template="normalize_bytecode",
        view_builder="cfg_blocks_df_builder",
    ),
    DatasetRegistrySpec(
        name="py_bc_cfg_edges_norm",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity",),
        fields=(
            "edge_id",
            "code_unit_id",
            "src_block_id",
            "dst_block_id",
            "kind",
            "cond_instr_id",
            "exc_index",
        ),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("code_unit_id", "edge_id"),
        template="normalize_bytecode",
        view_builder="cfg_edges_df_builder",
    ),
    DatasetRegistrySpec(
        name="py_bc_instr_norm",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity",),
        fields=(
            "instr_id",
            "code_unit_id",
            "offset",
            "opname",
            "arg",
            "arg_repr",
            "is_jump_target",
        ),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("code_unit_id", "instr_id"),
        template="normalize_bytecode",
        view_builder="instructions_df_builder",
    ),
    DatasetRegistrySpec(
        name="py_bc_exceptions_norm",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity",),
        fields=(
            "handler_id",
            "code_unit_id",
            "kind",
            "start_offset",
            "end_offset",
            "target_offset",
            "stack_depth",
            "stack_top",
        ),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("code_unit_id", "handler_id"),
        template="normalize_bytecode",
        view_builder="exception_handlers_df_builder",
    ),
    DatasetRegistrySpec(
        name="symtable_scopes",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=(
            "scope_id",
            "scope_name",
            "scope_kind",
            "scope_has_self",
            "scope_is_async",
            "scope_is_nested",
            "scope_is_generator",
            "scope_is_coroutine",
            "scope_is_comprehension",
            "scope_is_lambda",
            "scope_is_annotated",
            "scope_is_type_alias",
            "scope_is_docstring",
            "scope_is_exec",
            "scope_is_eval",
            "scope_is_function",
            "scope_is_class",
            "scope_is_module",
            "scope_is_import",
        ),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("scope_id",),
        template="normalize_symtable",
        view_builder="symtable_scopes_df_builder",
    ),
    DatasetRegistrySpec(
        name="symtable_symbols",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=(
            "symbol_id",
            "scope_id",
            "symbol_name",
            "symbol_flags",
            "symbol_is_assigned",
            "symbol_is_free",
            "symbol_is_global",
            "symbol_is_local",
            "symbol_is_parameter",
            "symbol_is_referenced",
            "symbol_is_imported",
            "symbol_is_nonlocal",
        ),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("scope_id", "symbol_name"),
        template="normalize_symtable",
        view_builder="symtable_symbols_df_builder",
    ),
    DatasetRegistrySpec(
        name="symtable_bindings",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=(
            "binding_id",
            "scope_id",
            "symbol_id",
            "binding_kind",
            "binding_name",
            "binding_order",
            "binding_is_global",
            "binding_is_import",
            "binding_is_parameter",
            "binding_is_nonlocal",
            "binding_is_referenced",
            "binding_is_annotated",
            "binding_is_assigned",
        ),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("binding_id",),
        template="normalize_symtable",
        view_builder="symtable_bindings_df_builder",
    ),
    DatasetRegistrySpec(
        name="symtable_def_sites",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=("scope_id", "binding_id", "def_id", "def_kind", "name"),
        category="analysis",
        supports_cdf=True,
        partition_cols=("path",),
        join_keys=("binding_id",),
        template="normalize_symtable",
        view_builder="symtable_def_sites_df_builder",
    ),
    DatasetRegistrySpec(
        name="scip_diagnostics",
        version=NORMALIZE_SCHEMA_VERSION,
        bundles=("file_identity", "span"),
        fields=(
            "diag_id",
            "severity",
            "message",
            "diag_source",
            "code",
            "details",
        ),
        category="diagnostic",
        supports_cdf=True,
        join_keys=("diag_id",),
        template="normalize_diagnostics",
        view_builder="diagnostics_df_builder",
    ),
)

__all__ = ["NORMALIZE_DATASETS", "NORMALIZE_SCHEMA_VERSION"]
