"""Thin facade for ast-grep query execution helpers."""

from __future__ import annotations

from tools.cq.query.executor_ast_grep_impl import (
    AstGrepExecutionContext,
    AstGrepExecutionState,
    AstGrepMatchSpan,
    AstGrepRuleContext,
    PatternFragmentContext,
    apply_metavar_details,
    assemble_pattern_output,
    build_match_data,
    build_pattern_fragment_context,
    coerce_int,
    collect_ast_grep_match_spans,
    collect_match_spans,
    collect_rule_prefilter_literals,
    decode_pattern_fragment_payload,
    execute_ast_grep_rules,
    execute_rule_matches,
    extract_match_metavars,
    filter_records_by_spans,
    group_match_spans,
    is_variadic_separator,
    match_passes_filters,
    match_to_finding,
    maybe_prefilter_pattern_paths,
    node_payload,
    parse_sgpy_metavariables,
    partition_query_metavar_filters,
    pattern_data_from_hits,
    pattern_fragment_entries,
    process_ast_grep_file,
    process_ast_grep_rule,
    resolve_rule_metavar_names,
    resolve_rule_variadic_metavars,
    run_ast_grep,
    strip_unsupported_sgpy_rule_keys,
)

__all__ = [
    "AstGrepExecutionContext",
    "AstGrepExecutionState",
    "AstGrepMatchSpan",
    "AstGrepRuleContext",
    "PatternFragmentContext",
    "apply_metavar_details",
    "assemble_pattern_output",
    "build_match_data",
    "build_pattern_fragment_context",
    "coerce_int",
    "collect_ast_grep_match_spans",
    "collect_match_spans",
    "collect_rule_prefilter_literals",
    "decode_pattern_fragment_payload",
    "execute_ast_grep_rules",
    "execute_rule_matches",
    "extract_match_metavars",
    "filter_records_by_spans",
    "group_match_spans",
    "is_variadic_separator",
    "match_passes_filters",
    "match_to_finding",
    "maybe_prefilter_pattern_paths",
    "node_payload",
    "parse_sgpy_metavariables",
    "partition_query_metavar_filters",
    "pattern_data_from_hits",
    "pattern_fragment_entries",
    "process_ast_grep_file",
    "process_ast_grep_rule",
    "resolve_rule_metavar_names",
    "resolve_rule_variadic_metavars",
    "run_ast_grep",
    "strip_unsupported_sgpy_rule_keys",
]
