from collections.abc import Mapping
from typing import Any

IS_STUB: bool

def plugin_library_path() -> str: ...
def plugin_manifest(path: str | None = ...) -> dict[str, object]: ...
def registry_snapshot(ctx: Any) -> Mapping[str, object]: ...
def udf_docs_snapshot(ctx: Any) -> Mapping[str, object]: ...
def install_function_factory(ctx: Any, policy_ipc: bytes) -> None: ...
def capabilities_snapshot() -> Mapping[str, object]: ...
def replay_substrait_plan(ctx: Any, payload_bytes: bytes) -> Any: ...
def lineage_from_substrait(payload_bytes: bytes) -> Mapping[str, object]: ...
def build_extraction_session(config_payload: Any) -> Any: ...
def register_dataset_provider(ctx: Any, request_payload: Any) -> Mapping[str, object]: ...
def arrow_stream_to_batches(obj: Any) -> Any: ...
def udf_expr(name: str, *args: Any, ctx: Any | None = ...) -> Any: ...
def load_df_plugin(path: str) -> Any: ...
def register_df_plugin_udfs(ctx: Any, plugin: Any, options_json: str | None = ...) -> None: ...
def register_df_plugin_table_functions(ctx: Any, plugin: Any) -> None: ...
def delta_scan_config_from_session(
    ctx: Any,
    file_column_name: str | None = ...,
    enable_parquet_pushdown: bool | None = ...,
    schema_force_view_types: bool | None = ...,
    wrap_partition_values: bool | None = ...,
    schema_ipc: bytes | None = ...,
) -> dict[str, object]: ...
def register_df_plugin_table_providers(
    ctx: Any,
    plugin: Any,
    table_names: list[str] | None = ...,
    options_json: dict[str, str] | None = ...,
) -> None: ...
def create_df_plugin_table_provider(
    plugin: Any, provider_name: str, options_json: str | None = ...
) -> Any: ...
def register_df_plugin(
    ctx: Any,
    plugin: Any,
    table_names: list[str] | None = ...,
    options_json: dict[str, str] | None = ...,
) -> None: ...
def __getattr__(name: str) -> Any: ...
