from datafusion import Expr, SessionContext

def register_udfs(
    ctx: SessionContext,
    *,
    enable_async: bool = ...,
    async_udf_timeout_ms: int | None = ...,
    async_udf_batch_size: int | None = ...,
) -> None: ...
def registry_snapshot(ctx: SessionContext) -> dict[str, object]: ...
def udf_docs_snapshot(ctx: SessionContext) -> dict[str, object]: ...
def map_entries(expr: Expr) -> Expr: ...
def map_keys(expr: Expr) -> Expr: ...
def map_values(expr: Expr) -> Expr: ...
def map_extract(expr: Expr, key: str) -> Expr: ...
def list_extract(expr: Expr, index: int) -> Expr: ...
def list_unique(expr: Expr) -> Expr: ...
def first_value_agg(expr: Expr) -> Expr: ...
def last_value_agg(expr: Expr) -> Expr: ...
def count_distinct_agg(expr: Expr) -> Expr: ...
def string_agg(value: Expr, delimiter: Expr) -> Expr: ...
def row_number_window(expr: Expr) -> Expr: ...
def lag_window(expr: Expr) -> Expr: ...
def lead_window(expr: Expr) -> Expr: ...
def arrow_metadata(expr: Expr, key: str | None = ...) -> Expr: ...
def union_tag(expr: Expr) -> Expr: ...
def union_extract(expr: Expr, tag: str) -> Expr: ...
def stable_hash64(value: Expr) -> Expr: ...
def stable_hash128(value: Expr) -> Expr: ...
def prefixed_hash64(prefix: str, value: Expr) -> Expr: ...
def stable_id(prefix: str, value: Expr) -> Expr: ...
def stable_id_parts(prefix: str, part1: Expr, *parts: Expr) -> Expr: ...
def semantic_tag(semantic_type: str, value: Expr) -> Expr: ...
def prefixed_hash_parts64(prefix: str, part1: Expr, *parts: Expr) -> Expr: ...
def stable_hash_any(
    value: Expr,
    canonical: bool | None = ...,
    null_sentinel: str | None = ...,
) -> Expr: ...
def span_make(
    bstart: Expr,
    bend: Expr,
    line_base: Expr | None = ...,
    col_unit: Expr | None = ...,
    end_exclusive: Expr | None = ...,
) -> Expr: ...
def span_len(span: Expr) -> Expr: ...
def span_overlaps(span_a: Expr, span_b: Expr) -> Expr: ...
def span_contains(span_a: Expr, span_b: Expr) -> Expr: ...
def interval_align_score(
    left_start: Expr,
    left_end: Expr,
    right_start: Expr,
    right_end: Expr,
) -> Expr: ...
def span_id(
    prefix: str,
    path: Expr,
    bstart: Expr,
    bend: Expr,
    kind: Expr | None = ...,
) -> Expr: ...
def utf8_normalize(
    value: Expr,
    form: str | None = ...,
    casefold: bool | None = ...,
    collapse_ws: bool | None = ...,
) -> Expr: ...
def utf8_null_if_blank(value: Expr) -> Expr: ...
def qname_normalize(
    symbol: Expr,
    module: Expr | None = ...,
    lang: Expr | None = ...,
) -> Expr: ...
def map_get_default(map_expr: Expr, key: str, default_value: Expr) -> Expr: ...
def map_normalize(
    map_expr: Expr,
    key_case: str | None = ...,
    sort_keys: bool | None = ...,
) -> Expr: ...
def list_compact(list_expr: Expr) -> Expr: ...
def list_unique_sorted(list_expr: Expr) -> Expr: ...
def struct_pick(
    struct_expr: Expr,
    field1: str,
    field2: str | None = ...,
    field3: str | None = ...,
    field4: str | None = ...,
    field5: str | None = ...,
    field6: str | None = ...,
) -> Expr: ...
def cdf_change_rank(change_type: Expr) -> Expr: ...
def cdf_is_upsert(change_type: Expr) -> Expr: ...
def cdf_is_delete(change_type: Expr) -> Expr: ...
def col_to_byte(line_text: Expr, col_index: Expr, col_unit: Expr) -> Expr: ...
