
from datafusion import Expr, SessionContext

def register_udfs(
    ctx: SessionContext,
    enable_async: bool = ...,
    async_udf_timeout_ms: int | None = ...,
    async_udf_batch_size: int | None = ...,
) -> None: ...

def registry_snapshot(ctx: SessionContext) -> dict[str, object]: ...

def udf_docs_snapshot(ctx: SessionContext) -> dict[str, object]: ...

def map_entries(expr: Expr) -> Expr: ...

def map_keys(expr: Expr) -> Expr: ...

def map_values(expr: Expr) -> Expr: ...

def map_extract(expr: Expr, key: str) -> Expr: ...

def list_extract(expr: Expr, index: int) -> Expr: ...

def list_unique(expr: Expr) -> Expr: ...

def first_value_agg(expr: Expr) -> Expr: ...

def last_value_agg(expr: Expr) -> Expr: ...

def count_distinct_agg(expr: Expr) -> Expr: ...

def string_agg(value: Expr, delimiter: Expr) -> Expr: ...

def row_number_window(expr: Expr) -> Expr: ...

def lag_window(expr: Expr) -> Expr: ...

def lead_window(expr: Expr) -> Expr: ...

def arrow_metadata(expr: Expr, key: str | None = ...) -> Expr: ...

def union_tag(expr: Expr) -> Expr: ...

def union_extract(expr: Expr, tag: str) -> Expr: ...

def stable_hash64(value: Expr) -> Expr: ...

def stable_hash128(value: Expr) -> Expr: ...

def prefixed_hash64(prefix: str, value: Expr) -> Expr: ...

def stable_id(prefix: str, value: Expr) -> Expr: ...

def col_to_byte(line_text: Expr, col_index: Expr, col_unit: Expr) -> Expr: ...
